apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
spec:
  source:
    repoURL: 'https://github.com/komal-singh007/udacity'
    targetRevision: HEAD
    path: project/helm
    helm:
      valueFiles:
      - values-staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  project: default
