namespace:
  name: sandbox

appname: techtrends
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: komalsingh000/techtrends:latest
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 3111


  limits:
    memory: 128Mi
    cpu: 500m



livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111
